# Generated by Django 4.2.2 on 2023-06-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='lastPart',
            field=models.BooleanField(default=False),
        ),
    ]
