# Generated by Django 4.2.2 on 2023-06-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_data_lastpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAPIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('update', models.BooleanField(default=False)),
                ('lastPart', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SummariesAPIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('update', models.BooleanField(default=False)),
            ],
        ),
    ]
